[package]
name = "bench"
version = "0.1.0"
authors = ["Armin Ronacher <armin.ronacher@active-4.com>"]

[dependencies]
sha1 = { path = ".." }
ring = "*"
openssl = "*"
rust-crypto = "*"

[[bin]]
name = "bench"
path = "bench.rs"
